# Generated by Django 4.2.16 on 2024-10-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_acqusitiondatesinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acqusitiondatesinfo',
            name='satellite',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='satelliteacqusition',
            name='satellite',
            field=models.CharField(max_length=20),
        ),
    ]
