version: '3.8'

services:
  redis:
    image: redis:7.0.11-alpine

  backend:
    container_name: backend
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8001:8000
    depends_on:
      - redis

  arequests:
    container_name: arequests
    build:
      context: ./backend
    command: python api/aws2.py
    env_file:
      - .env
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - redis

  celery:
    container_name: celery
    build:
      context: ./backend
    command: celery --app=backend worker -l INFO --logfile=logs/celery.log
    env_file:
      - .env
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - redis
      - backend

  dashboard:
    build: ./backend
    command: celery --app=backend --broker=redis://redis:6379/0 flower --port=5000 
    env_file:
      - .env
    ports:
      - 5000:5555
    depends_on:
      - backend
      - redis
      - celery
